---
title: "Tidy Tuesday 4"
author: "Manroop"
date: "3/23/2022"
output: html_document
---

# Load Libraries #
```{r}
library(tidyverse)
library(ggtext)
library(patchwork)
library(showtext)
```
# Load Data #
```{r}
freedom <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-22/freedom.csv')
glimpse(freedom)
font_add_google(name = "Space Mono", family = "space")
showtext_auto()
```
```{r}
continent_status <- freedom %>% 
  filter(year == 2020) %>% 
  select(continent = Region_Name, 
         status = Status) %>% 
  group_by(continent) %>% 
  mutate(free_countries = sum(status == "F"),
         total = n()) %>% 
  filter(row_number() == 1) %>% 
  select(continent, free_countries, total) %>% 
  mutate(free_fraction = free_countries / total) %>% 
  mutate(non_free_fraction = 1 - free_fraction) %>% 
  select(continent, free_fraction, non_free_fraction) %>% 
  pivot_longer(-continent, names_to = "status", values_to = "fraction") %>% 
  mutate(status = str_remove(status, "_fraction")) %>% 
  group_by(continent) %>% 
  mutate(ymin = case_when(status == "non_free" ~ 1 - fraction, TRUE ~ 0),  ymax = case_when(status == "free" ~ fraction, TRUE ~ 1))
glimpse(continent_status)
```
```{r}
europe <- continent_status %>%
  filter(continent == "Europe")%>%
  ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=status)) +
  geom_rect(show.legend = FALSE, fill = purple) +
  geom_text( x=2, aes(y=labelPosition, label=label, color=category), size=6) + # x here controls label position (inner / outer)
  scale_fill_brewer(palette=3) +
  scale_color_brewer(palette=3) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
```



