---
title: "Tidy Tuesday 3 Dogs"
author: "Manroop"
date: "3/22/2022"
output: html_document
---
# Load Libraries #
```{r}
library(tidyverse)
library(here)
library(PNWColors) 
library(ggplot2)
```

```{r}
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv') 
```
```{r}
Sib<-breed_traits[16,]
Sib<-Sib[,-8]
Sib<-Sib[,-8]

Sib<- Sib %>% pivot_longer(cols=!Breed, names_to = "trait",values_to = "rate") #Make traits columns
Sib <- rbind(rep(0,14) , rep(5,14) , Sib )
levels<- Sib$trait
```


```{r}
ggplot(data=Sib, aes(x = rate, y = trait)) +
  geom_bar(colour="white", fill="hotpink", width=.8, stat="identity")+ 
  theme_classic()+ 
  labs(x = "Rating", 
       y = "Trait")+ 
  ggtitle("Siberian Husky Ratings")+ 
  theme(panel.background = element_rect(fill = "white"), 
        axis.text.x= element_text(size=8), 
        axis.text.y= element_text(size = 8), 
        plot.title = element_text(face = "bold",
                                   size = 12))
ggsave(here("Tidy Tuesday 3", "Output", "Husky.png"))
```


