---
title: "Tidy Tuesday 2"
author: "Manroop"
date: "3/22/2022"
output: html_document
---


```{r}
library(tidyverse)
library(stringr)
library(gganimate)
chocolate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-18/chocolate.csv')
install.packages("transformr")
library(transformr)
```

#### Cleaning Data ####
```{r}
chocolate_s <- chocolate %>%
  mutate( num_ingredients = as.integer
          (str_extract(ingredients, "[:digit:]")),
    cocoa_percent_num = as.integer
    (str_extract(cocoa_percent, "[:digit:]{1,3}"))) %>% 
  select(review_date, 
         cocoa_percent_num, 
         rating)

cocoa_tertiles <- quantile(chocolate_small$cocoa_percent_num)
cocoa_quintiles <- quantile(chocolate_small$cocoa_percent_num)

chocolate_s <- chocolate_s %>% 
  mutate(cocoa_group = case_when(
    cocoa_percent_num >= cocoa_tertiles[3] ~ "High",
    cocoa_percent_num <= cocoa_tertiles[2] ~ "Low")) %>% 
  select(review_date, cocoa_group, rating) %>% 
  group_by(review_date, cocoa_group) %>% 
  summarize(mean_rating = mean(rating))
```


#### Plot ####
```{r}
chocolate_s %>% 
  ggplot(., aes(x = review_date, y = mean_rating))+
  geom_line(color="brown", size=1.5) + 
  transition_filter(`Low Cocoa` = cocoa_group == "Low", 
                    `High Cocoa` = cocoa_group == "High" ) +
  ease_aes('cubic-in-out') +
  labs(title = "Chocolate Bar Ratings by Year", subtitle="Bars with {closest_filter}", y = "Mean Rating", x = "Year") 
anim_save(here("Tidy Tuesday 2","Output","ChocoRating.gif"))
```

